### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = https://fxjney46mbeijjyti3ysri6afi.appsync-api.us-west-2.amazonaws.com/graphql
@auth_token = {{$dotenv REACT_APP_AUTH_RENTALSCAPE}}

#####################
### GET PROPERTIES (HOUSES) BY REGION
# @name GetRegionHouses

POST {{ baseUrl }}
Content-Type: application/json
Authorization: Bearer {{ auth_token }}
X-REQUEST-TYPE: GraphQL

query GetRegionHouses($regionId: String!, $nextToken: String) {
  region: getRegion(regionName: $regionId) {
    properties(
      limit: 3
      nextToken: $nextToken
      filter: { address: { size: { gt: 0 } } }
    ) {
      nextToken
      items {
        ...PropertyFragment
      }
    }
  }
}
fragment PropertyFragment on Property {
  deckardId
  displayInfo {
    label
    value
  }
  isLicensed
  types
  geo {
    lat
    lng
  }
  geo5
  address
  contact {
    ...PropertyContactInfo
  }
  licenses {
    items {
      ...LicenseInfo
    }
  }
  listings {
    items {
      ...ListingInfo
    }
  }
}
fragment PropertyContactInfo on PropertyContact {
  name
  phone
  email
  company
}
fragment LicenseInfo on License {
  license_id
  propertyLicensesId
  num_bedrooms
  num_vehicles
  occupancy
  status
  contacts {
    ...LicenseContactFragment
  }
}
fragment LicenseContactFragment on LicenseContact {
  type
  name
  phone
  email
  company
}
fragment ListingInfo on Listing {
  active
  verified
  imageUrls
}

### variables
{
  "regionId": "ca-placer"
}
