### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = https://fxjney46mbeijjyti3ysri6afi.appsync-api.us-west-2.amazonaws.com/graphql
@auth_token = {{$dotenv REACT_APP_AUTH_RENTALSCAPE}}

#######################
### GET REGION DETAILS
# @name GetRegionDetails

POST {{ baseUrl }}
Content-Type: application/json
Authorization: Bearer {{ auth_token }}
X-REQUEST-TYPE: GraphQL

query GetRegionDetails($regionShortName: String!) {
  region: regionByShortName(regionShortName: $regionShortName) {
    items {
      regionName
      name
      logo
      misc
      geoJson
      legends {
        ...LegendData
      }
      statistics {
        ...StatData
      }
      links {
        ...LinkData
      }
    }
  }
}
fragment LegendData on Legend {
  colorHex
  count
  formattedText
  tooltip
  propertyType
}
fragment StatData on RegionStatistic {
  type
  value
}
fragment LinkData on Link {
  displayValue
  label
  tooltip
  type
  value
}

### variables
{
  "regionShortName": "placer-ca"
}
