### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = {{$dotenv REACT_APP_GRAPHQL_RENTALSCAPE}}
@auth_token = {{$dotenv REACT_APP_AUTH_RENTALSCAPE}}

######################
### LIST REGIONS
# @name GetRegionNames

POST {{ baseUrl }}
Content-Type: application/json
Authorization: Bearer {{ auth_token }}
X-REQUEST-TYPE: GraphQL

query GetRegionNames {
  listRegions {
    items {
      name
      regionShortName
    }
  }
}
