### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = http://localhost:{{$dotenv EXPRESS_PORT}}/graphql
@auth_token = {{$dotenv JWT_AUTH_TOKEN}}

######################
### Gets all cities by name
# @name GetCitiesByName

POST {{ baseUrl }}
Content-Type: application/json
Authorization: Bearer {{ auth_token }}
X-REQUEST-TYPE: GraphQL

query GetCitiesByName($name: String!) {
  getCitiesByName(name: $name) {
    message
    result {
      name
      lat
      lng
      country
      countryInfo {
        name
        native
        phone
        continent
        capital
        currency
        languages
      }
    }
  }
}

### variables
{
  "name": "San cristobal"
}
